test_that("sync previews, applies and preserves user content and pins", {
  parent <- new_parent()
  p <- project("Sync", "methods", "Original goal", parent)
  manuscript <- file.path(p$path, "publications/pub01_main/manuscript/README.md")
  writeLines("Reviewed manuscript", manuscript)
  before <- tree_hashes(p$path)
  preview <- sync(p$path, options = list(project = list(goal = "Updated goal")))
  expect_identical(tree_hashes(p$path), before)
  expect_equal(preview$state, "planned")
  expect_length(preview$conflicts, 0)
  result <- sync(p$path, options = list(project = list(goal = "Updated goal")), dry_run = FALSE)
  expect_equal(result$state, "applied")
  accepted <- validate_spec(file.path(p$path, "cttir-project.yml"))
  expect_equal(accepted$project$goal, "Updated goal")
  expect_equal(accepted$project$id, p$spec$project$id)
  expect_equal(readLines(manuscript), "Reviewed manuscript")
  expect_equal(
    read_project(p$path)$lock$resource_snapshot,
    jsonlite::fromJSON(system.file("extdata/resource-manifest.json", package = "cttiR"))$content_id
  )
  after <- tree_hashes(p$path)
  expect_length(sync(p$path, dry_run = FALSE)$changed_files, 0)
  expect_identical(tree_hashes(p$path), after)
})

test_that("sync conflicts and path attacks cause no writes", {
  parent <- new_parent()
  p <- project("Conflict", "methods", "Goal", parent)
  writeLines("aim: reviewed", file.path(p$path, "config/analysis.yml"))
  before <- tree_hashes(p$path)
  s <- sync(p$path, options = list(analysis = list(aim = "descriptive")), dry_run = FALSE)
  expect_equal(s$state, "conflict")
  expect_contains(s$conflicts, "config/analysis.yml")
  expect_identical(tree_hashes(p$path), before)
  expect_error(sync(p$path, options = list(project = list(slug = "elsewhere"))), class = "cttir_input_error")
  expect_error(sync(p$path, options = list(publications = list())), class = "cttir_path_conflict")
  expect_error(sync(p$path, options = list(publications = list(list(id = "pub01", slug = "renamed")))), class = "cttir_path_conflict")
  if (.Platform$OS.type != "windows") {
    unlink(file.path(p$path, "config/analysis.yml"))
    external <- file.path(parent, "external")
    writeLines("Keep external", external)
    expect_true(file.link(external, file.path(p$path, "config/analysis.yml")))
    expect_error(sync(p$path, dry_run = FALSE), class = "cttir_path_conflict")
    expect_equal(readLines(external), "Keep external")
  }
})

test_that("a failed replacement rolls back completed writes and retains evidence", {
  parent <- new_parent()
  p <- project("Rollback", "methods", "Goal", parent)
  before <- tree_hashes(p$path)
  calls <- 0L
  real <- replace_file
  testthat::local_mocked_bindings(replace_file = function(from, to) {
    calls <<- calls + 1L
    if (calls == 2L) stop("injected I/O failure")
    real(from, to)
  })
  expect_error(sync(p$path, options = list(analysis = list(aim = "descriptive")), dry_run = FALSE), "injected")
  after <- tree_hashes(p$path)
  expect_identical(after[names(before)], before)
  journals <- list.files(file.path(p$path, ".cttir/transactions"), "journal.json", recursive = TRUE, full.names = TRUE)
  expect_length(journals, 1)
  expect_equal(read_document(journals[[1]])$status, "rolled_back")
  expect_false(dir.exists(file.path(p$path, ".cttir/write-lock")))
})

test_that("background apply refuses a changed reviewed file plan", {
  parent <- new_parent()
  p <- project("Reviewed sync", "methods", "Goal", parent)
  config <- list(project = list(language = "de"))
  plan <- sync(p$path, config = config)
  hash <- content_hash(json_text(plan$actions))
  file <- file.path(p$path, "cttir-project.yml")
  writeLines(c(readLines(file), "# intervening edit"), file)
  before <- tree_hashes(p$path)
  expect_error(sync_impl(p$path, config = config, dry_run = FALSE, expected_plan = hash), class = "cttir_transaction_conflict")
  expect_identical(tree_hashes(p$path), before)
})

test_that("an edited managed file is kept when its rendering does not change", {
  p <- project("Own Eps", "primary_research", "Compare blood pressure between two groups", new_parent())
  readme <- file.path(p$path, "README.md")
  cat("\nMy notes\n", file = readme, append = TRUE)
  edited <- file_hash(readme)
  s <- sync(p$path, options = list(workflow = list(pipeline = "targets")), dry_run = FALSE)
  expect_equal(s$state, "applied")
  expect_length(s$conflicts, 0L)
  expect_contains(s$preserved, "README.md")
  expect_equal(s$actions$reason[s$actions$path == "README.md"], "edit_kept_rendering_unchanged")
  expect_true(file.exists(file.path(p$path, "_targets.R")))
  expect_equal(file_hash(readme), edited)
  # Once both the user and the rendering change a managed file, it conflicts.
  config <- file.path(p$path, "config/workflow.yml")
  cat("\n# my edit\n", file = config, append = TRUE)
  conflict <- sync(p$path, options = list(workflow = list(pipeline = "none")), dry_run = FALSE)
  expect_equal(conflict$state, "conflict")
  expect_identical(conflict$conflicts, "config/workflow.yml")
  expect_output(print(conflict), "1 conflicts")
})

test_that("unedited user-owned derived files follow the spec and edited ones get a proposal", {
  p <- project("Own Zeta", "mixed", "Compare blood pressure between two groups", new_parent())
  registry <- file.path(p$path, "metadata/data-registry.yml")
  source <- list(id = "ds1", label = "Cohort", logical_uri = "registry://cohort", format = "csv",
    access_class = "restricted", checksum = NULL, checksum_status = "unknown", schema_ref = NULL)
  added <- sync(p$path, options = list(data_sources = list(source)), dry_run = FALSE)
  expect_equal(added$actions$action[added$actions$path == "metadata/data-registry.yml"], "update")
  expect_equal(read_document(registry)$datasets[[1]]$id, "ds1")
  expect_equal(nrow(added$pending_updates), 0L)
  publication <- file.path(p$path, "publications/pub01_main/publication.yml")
  reclassified <- sync(p$path, options = list(publications = list(list(id = "pub01", research_class = "methods"))),
    dry_run = FALSE)
  expect_contains(reclassified$changed_files, "publications/pub01_main/publication.yml")
  expect_equal(read_document(publication)$research_class, "methods")
  # A user edit is never overwritten; the update is reported and proposed.
  cat("# reviewed by the data manager\n", file = registry, append = TRUE)
  edited <- file_hash(registry)
  source$label <- "Cohort 2026"
  preview <- sync(p$path, options = list(data_sources = list(source)))
  expect_equal(preview$pending_updates$path, "metadata/data-registry.yml")
  expect_output(print(preview), "1 pending updates")
  expect_false(file.exists(file.path(p$path, ".cttir/proposed/metadata/data-registry.yml")))
  applied <- sync(p$path, options = list(data_sources = list(source)), dry_run = FALSE)
  expect_equal(applied$state, "applied")
  expect_equal(file_hash(registry), edited)
  expect_equal(applied$pending_updates$proposal, ".cttir/proposed/metadata/data-registry.yml")
  proposal <- read_document(file.path(p$path, ".cttir/proposed/metadata/data-registry.yml"))
  expect_equal(proposal$datasets[[1]]$label, "Cohort 2026")
  expect_output(print(applied), "Kept your edits")
  # The pending update stays visible until the user resolves it.
  again <- sync(p$path)
  expect_equal(again$pending_updates$path, "metadata/data-registry.yml")
  file.copy(file.path(p$path, ".cttir/proposed/metadata/data-registry.yml"), registry, overwrite = TRUE)
  resolved <- sync(p$path, dry_run = FALSE)
  expect_equal(nrow(resolved$pending_updates), 0L)
  manifest <- read_project(p$path)$manifest$files
  entry <- Filter(function(x) identical(x$path, "metadata/data-registry.yml"), manifest)[[1]]
  expect_equal(entry$baseline_sha256, file_hash(registry))
  expect_equal(entry$ownership, "user")
})

test_that("a hand-edited cttir-project.yml is previewed, validated and accepted by sync", {
  parent <- new_parent()
  p <- project("Hand Edit", "primary_research", "Describe a cohort", parent, options = list(research = list(design = "cohort")))
  file <- file.path(p$path, "cttir-project.yml")
  accepted <- readLines(file)
  edit <- function(pattern, replacement) writeLines(sub(pattern, replacement, accepted), file)
  edit("^  design: .*", "  design: case-control")
  expect_error(project("Hand Edit", "primary_research", "Describe a cohort", parent), "edited after it was last accepted",
    class = "cttir_schema_error")
  report <- audit(p$path, scope = "project")
  expect_match(report$checks$message[report$checks$id == "PRJ-001"], "cttiR::sync", fixed = TRUE)
  before <- tree_hashes(p$path)
  preview <- sync(p$path)
  expect_identical(tree_hashes(p$path), before)
  expect_equal(preview$spec_edit$state, "previewed")
  expect_equal(preview$spec_edit$changes$pointer, "/research/design")
  expect_equal(preview$actions$reason[preview$actions$path == "cttir-project.yml"], "accepted_hand_edit")
  expect_output(print(preview), "Hand edit of cttir-project.yml: previewed")
  applied <- sync(p$path, dry_run = FALSE)
  expect_equal(applied$spec_edit$state, "accepted")
  spec <- read_project(p$path)$spec
  expect_equal(spec$research$design, "case-control")
  expect_match(spec$decisions[[length(spec$decisions)]]$reason, "hand edit")
  expect_true(all(project("Hand Edit", "primary_research", "Describe a cohort", parent)$plan$action == "skip"))
  # Explicit options of the same call take precedence over the hand edit.
  accepted <- readLines(file)
  edit("^  design: .*", "  design: cross-sectional")
  sync(p$path, options = list(research = list(design = "registry")), dry_run = FALSE)
  expect_equal(read_project(p$path)$spec$research$design, "registry")
  accepted <- readLines(file)
  code <- function(expr) tryCatch(expr, error = function(e) c(e$code, paste(e$field, collapse = ""), e$remediation))
  edit("^  ethics_status: .*", "  ethics_status: maybe")
  invalid <- code(sync(p$path))
  expect_equal(invalid[1:2], c("schema_validation", "/research/ethics_status"))
  expect_match(invalid[[3]], "Correct /research/ethics_status in cttir-project.yml")
  edit("^  slug: hand_edit$", "  slug: renamed")
  expect_equal(code(sync(p$path))[1:2], c("invalid_spec_edit", "/project/slug"))
  edit("^  design: .*", "  design: ''")
  expect_equal(code(sync(p$path))[1:2], c("empty_value", "/research/design"))
  edit("^  readiness: .*", "  readiness: environment_ready")
  expect_equal(code(sync(p$path))[1:2], c("invalid_input", "/workflow/readiness"))
  start <- grep("^publications:", accepted)
  writeLines(c(accepted[seq_len(start - 1L)], "publications: []", accepted[-seq_len(grep("^workflow:", accepted) - 1L)]), file)
  expect_error(sync(p$path), "requires an explicit archive plan", class = "cttir_path_conflict")
  writeLines(accepted, file)
  expect_equal(sync(p$path)$state, "planned")
  # Without the verified accepted copy, a hand edit cannot be reviewed.
  unlink(file.path(p$path, ".cttir/accepted-spec.yml"))
  edit("^  design: .*", "  design: case-control")
  expect_equal(code(sync(p$path))[[1]], "spec_edit_unverifiable")
})

test_that("sync names the project root and refuses empty answers", {
  p <- project("Roots", "methods", "Goal", new_parent())
  expect_error(sync(file.path(p$path, "code")), "is inside the project", class = "cttir_path_conflict")
  expect_error(sync(dirname(p$path)), "not the root of a cttiR project", class = "cttir_path_conflict")
  err <- expect_error(sync(p$path, options = list(research = list(design = ""))), class = "cttir_input_error")
  expect_equal(err$field, "/research/design")
  expect_error(project("Empty", "methods", "Goal", new_parent(), options = list(research = list(design = " ")), dry_run = TRUE),
    "/research/design is an empty string", class = "cttir_input_error")
  unknown <- project("Unknown", "methods", "Goal", new_parent(), options = list(research = list(design = NULL)), dry_run = TRUE)
  expect_null(unknown$spec$research$design)
})

test_that("files that differ from their baseline only by CRLF line endings are not edits", {
  p <- project("Line endings", "methods", "Goal", new_parent())
  crlf <- function(file) {
    lines <- readLines(file)
    writeBin(charToRaw(paste0(paste(lines, collapse = "\r\n"), "\r\n")), file)
  }
  crlf(file.path(p$path, "config/analysis.yml"))
  crlf(file.path(p$path, "cttir-project.yml"))
  expect_equal(sync(p$path)$state, "planned")
  applied <- sync(p$path, options = list(analysis = list(aim = "descriptive")), dry_run = FALSE)
  expect_equal(applied$state, "applied")
  expect_equal(read_project(p$path)$spec$analysis$aim, "descriptive")
})
