test_that("three-input creation is offline, useful and idempotent", {
  parent <- new_parent()
  before_rng <- if (exists(".Random.seed", .GlobalEnv)) get(".Random.seed", .GlobalEnv) else NULL
  before_wd <- getwd()
  before_lib <- .libPaths()
  preview <- project("Example Study", "primary_research", "Describe outcomes", parent, dry_run = TRUE)
  expect_length(list.files(parent, all.files = TRUE, no.. = TRUE), 0)
  expect_false(preview$readiness$materialized)
  p <- project("Example Study", "primary_research", "Describe outcomes", parent)
  expect_equal(p$path, file.path(normalizePath(parent, winslash = "/"), "example_study"))
  expect_equal(p$spec$research$ethics_status, "unknown")
  expect_false(p$spec$analysis$approved)
  expect_true(file.exists(file.path(p$path, "publications/pub01_main/manuscript/README.md")))
  expect_true(file.exists(file.path(p$path, "code/validate_project.R")))
  expect_silent(validate_spec(file.path(p$path, "cttir-project.yml")))
  original <- tree_hashes(p$path)
  repeat_p <- project("Example Study", "primary_research", "Describe outcomes", parent)
  expect_identical(tree_hashes(p$path), original)
  expect_identical(p$spec, repeat_p$spec)
  expect_true(all(repeat_p$plan$action == "skip"))
  expect_equal(getwd(), before_wd)
  expect_equal(.libPaths(), before_lib)
  expect_identical(if (exists(".Random.seed", .GlobalEnv)) get(".Random.seed", .GlobalEnv) else NULL, before_rng)
  expect_error(project("Example Study", "methods", "Changed goal", parent), class = "cttir_path_conflict")
  expect_identical(tree_hashes(p$path), original)
})

test_that("user edits survive identical creation and dry run", {
  parent <- new_parent()
  p <- project("Edits", "methods", "Preserve work", parent)
  writeLines("Reviewed manuscript", file.path(p$path, "publications/pub01_main/manuscript/README.md"))
  writeLines("# Custom validation", file.path(p$path, "code/validate_project.R"))
  before <- tree_hashes(p$path)
  rerun <- project("Edits", "methods", "Preserve work", parent)
  expect_contains(rerun$warnings, "existing_edits_preserved")
  expect_identical(tree_hashes(p$path), before)
  expect_s3_class(project("Edits", "methods", "Preserve work", parent, dry_run = TRUE), "cttir_project")
  expect_identical(tree_hashes(p$path), before)
  unlink(file.path(p$path, "cttir-lock.json"))
  expect_error(project("Edits", "methods", "Preserve work", parent), class = "cttir_path_conflict")
})

test_that("unsafe paths, symlinks and writer collisions are contained", {
  parent <- new_parent()
  for (name in c("../escape", "CON", "a/b", "a\\b", "..", "nul", "com1")) {
    expect_error(project(name, "methods", "Goal", parent), class = "cttir_input_error")
  }
  writeLines("Keep me", file.path(parent, "collision"))
  expect_error(project("Collision", "methods", "Goal", parent), class = "cttir_path_conflict")
  dir.create(file.path(parent, ".locked.cttir-create-lock"))
  expect_error(project("Locked", "methods", "Goal", parent), class = "cttir_transaction_conflict")
  expect_false(dir.exists(file.path(parent, "locked")))
  expect_equal(readLines(file.path(parent, "collision")), "Keep me")
  if (.Platform$OS.type != "windows") {
    outside <- new_parent()
    expect_true(file.symlink(outside, file.path(parent, "linked")))
    expect_error(project("Linked", "methods", "Goal", parent), class = "cttir_path_conflict")
    expect_error(project("New", "methods", "Goal", file.path(parent, "linked")), class = "cttir_path_conflict")
    expect_length(list.files(outside, all.files = TRUE, no.. = TRUE), 0)
  }
})

test_that("unicode is retained as data and generated R remains fixed", {
  parent <- new_parent()
  p <- project("München Study", "mixed", "```r print('no execution') ``` <script>bad()</script>", parent)
  expect_identical(p$spec$project$name, "München Study")
  code <- paste(readLines(file.path(p$path, "code/validate_project.R")), collapse = "\n")
  expect_false(grepl("no execution|<script>", code))
  expect_type(parse(text = code), "expression")
})
