stop_catalog_writer <- function(root, pid, journal = NULL) {
  dir.create(file.path(root, "write-lock"), recursive = TRUE, showWarnings = FALSE)
  write_bytes(json_text(list(pid = pid, host = Sys.info()[["nodename"]])), file.path(root, "write-lock/owner.json"))
  if (!is.null(journal)) write_bytes(json_text(journal), file.path(root, "write-lock/activation.json"))
}

test_that("stopped catalog writers retain evidence and recover a complete active snapshot", {
  skip_if_not_installed("callr")
  f <- local_update_fixture()
  update()
  pointer <- current_catalog_manifest()
  stop_catalog_writer(f$store, callr::r(function() Sys.getpid()), list(schema_version = 1L, previous = pointer, candidate = pointer))
  expect_equal(update()$status, "unchanged")
  expect_identical(current_catalog_manifest(), pointer)
  expect_false(dir.exists(file.path(f$store, "write-lock")))
  retained <- list.dirs(file.path(f$store, "recovered-locks"), recursive = FALSE)
  expect_length(retained, 1L)
  expect_true(file.exists(file.path(retained, "activation.json")))
})

test_that("catalog recovery never bypasses live or unknown writers", {
  f <- local_update_fixture()
  update()
  stop_catalog_writer(f$store, Sys.getpid())
  before <- tree_hashes(f$store)
  expect_error(update(), "still running", class = "cttir_transaction_conflict")
  expect_identical(tree_hashes(f$store), before)
  unlink(file.path(f$store, "write-lock/owner.json"))
  expect_error(update(), "unknown", class = "cttir_transaction_conflict")
})

test_that("staging recovery keeps old snapshots and rejects corrupt pointers", {
  skip_if_not_installed("callr")
  f <- local_update_fixture()
  update()
  dead <- callr::r(function() Sys.getpid())
  stop_catalog_writer(f$store, dead)
  writeLines("broken", file.path(f$store, "active.json"))
  before <- tree_hashes(f$store)
  expect_error(update())
  expect_identical(tree_hashes(f$store), before)
  expect_true(dir.exists(file.path(f$store, "write-lock")))
  expect_false(dir.exists(file.path(f$store, "recovery-lock")))
})

test_that("a reader preview never repairs or removes a writer lock", {
  skip_if_not_installed("callr")
  f <- local_update_fixture()
  update()
  stop_catalog_writer(f$store, callr::r(function() Sys.getpid()))
  before <- tree_hashes(f$store)
  expect_equal(update(dry_run = TRUE)$status, "planned")
  expect_identical(tree_hashes(f$store), before)
})

test_that("recovery accepts only the recorded active preimage or postimage", {
  skip_if_not_installed("callr")
  f <- local_update_fixture()
  update()
  old <- current_catalog_manifest()
  absent <- snapshot_manifest(paste(rep("0", 64), collapse = ""), old$resource_id)
  pid <- callr::r(function() Sys.getpid())
  stop_catalog_writer(f$store, pid, list(schema_version = 1L, previous = absent, candidate = absent))
  before <- tree_hashes(f$store)
  expect_error(update(), "does not match", class = "cttir_transaction_conflict")
  expect_identical(tree_hashes(f$store), before)
  stop_catalog_writer(f$store, pid, list(schema_version = 1L, previous = old, candidate = absent))
  expect_equal(update()$status, "unchanged")
  expect_identical(current_catalog_manifest(), old)
})
