counting_worker <- function(counter) {
  counter$calls <- character()
  function(operation, args) {
    counter$calls <- c(counter$calls, operation)
    app_test_worker(operation, args)
  }
}

test_that("Ask renders grounded evidence, escapes text and never runs returned code", {
  skip_if_not_installed("shiny")
  shiny::testServer(app_ask_server, args = app_test_args(), {
    session$setInputs(action = "ask", question = "", verified_only = TRUE, use_project = FALSE, limit = 20)
    session$setInputs(run = 1)
    expect_equal(state$status$key, "ask.empty")
    session$setInputs(question = "annotatR <script>alert(1)</script>", run = 2)
    expect_s3_class(state$result, "cttir_answer")
    html <- as.character(output$result$html)
    expect_false(grepl("<script>alert", html, fixed = TRUE))
    expect_match(html, "Limitations", fixed = TRUE)
    session$setInputs(action = "search", question = "annotatR", run = 3)
    expect_s3_class(state$result, "data.frame")
    expect_match(as.character(output$result$html), "Search results", fixed = TRUE)
  })
  fields <- list(answer = "Use the reviewed adapter.", steps = list("pkg::fn(x)"),
    code = "file.create('/tmp/cttir-should-never-exist')", citations = list("https://example.org/doc", "javascript:alert(1)"),
    verification_levels = "static_api_verified", evidence = data.frame(), limitations = "Synthetic.",
    future_field = list(note = "added by a newer ask()"))
  answer <- structure(fields, class = "cttir_answer")
  worker <- function(operation, args) {
    list(is_alive = function() FALSE, get_result = function() list(ok = TRUE, value = answer), kill = function() NULL)
  }
  shiny::testServer(app_ask_server, args = app_test_args(worker), {
    session$setInputs(action = "ask", question = "How?", verified_only = TRUE, use_project = FALSE, run = 1)
    html <- as.character(output$result$html)
    expect_match(html, "file.create", fixed = TRUE)
    expect_match(html, "data-copy-target", fixed = TRUE)
    expect_match(html, 'href="https://example.org/doc"', fixed = TRUE)
    expect_false(grepl('href="javascript', html, fixed = TRUE))
    expect_match(html, "Other details", fixed = TRUE)
    expect_match(html, "added by a newer ask()", fixed = TRUE)
  })
  expect_false(file.exists("/tmp/cttir-should-never-exist"))
})

test_that("Knowledge previews and applies an update against a temporary store, then rolls back", {
  skip_if_not_installed("shiny")
  f <- local_update_fixture()
  shiny::testServer(app_knowledge_server, args = app_test_args(), {
    session$setInputs(use_project = FALSE, load_packages = 1)
    expect_s3_class(state$packages, "data.frame")
    expect_match(as.character(output$packages$html), "Exports", fixed = TRUE)
    session$setInputs(mode = "local", catalogs = c("knowledge", "resources"), sources = "", packages_filter = "")
    session$setInputs(apply_update = 1)
    expect_equal(state$status$key, "knowledge.preview_first")
    before <- current_catalog_manifest()$manifest_id
    session$setInputs(preview_update = 1)
    expect_equal(state$update_preview$status, "planned")
    expect_identical(state$update_preview$previous_id, before)
    expect_identical(current_catalog_manifest()$manifest_id, before)
    html <- as.character(output$update_result$html)
    expect_match(html, "package_added", fixed = TRUE)
    expect_match(html, "No package is installed", fixed = TRUE)
    session$setInputs(sources = "fixture")
    session$setInputs(apply_update = 2)
    expect_equal(state$status$key, "knowledge.preview_first")
    session$setInputs(sources = "")
    session$setInputs(apply_update = 3)
    expect_true(state$update_result$activation)
    after <- current_catalog_manifest()$manifest_id
    expect_false(identical(after, before))
    session$setInputs(rollback_id = before, preview_rollback = 1)
    expect_equal(state$rollback_preview$status, "planned")
    expect_identical(current_catalog_manifest()$manifest_id, after)
    session$setInputs(apply_rollback = 1)
    expect_equal(state$status$key, "knowledge.rollback_applied")
    expect_identical(current_catalog_manifest()$manifest_id, before)
  })
})

test_that("Knowledge refuses to apply a preview whose base catalog changed", {
  skip_if_not_installed("shiny")
  f <- local_update_fixture()
  shiny::testServer(app_knowledge_server, args = app_test_args(), {
    session$setInputs(mode = "local", catalogs = "knowledge", sources = "", packages_filter = "", preview_update = 1)
    expect_false(is.null(state$update_preview))
    update(dry_run = FALSE)
    changed <- current_catalog_manifest()$manifest_id
    session$setInputs(apply_update = 1)
    expect_equal(state$status$key, "knowledge.base_changed")
    expect_null(state$update_result)
    expect_identical(current_catalog_manifest()$manifest_id, changed)
    session$setInputs(catalogs = character(0))
    session$setInputs(preview_update = 2)
    expect_equal(state$status$key, "knowledge.catalogs_required")
  })
})

test_that("Resources load lazily and apply domain, repository and maturity filters", {
  skip_if_not_installed("shiny")
  counter <- new.env(parent = emptyenv())
  visible <- shiny::reactiveVal(FALSE)
  shiny::testServer(app_resources_server, args = app_test_args(counting_worker(counter), visible = visible), {
    session$setInputs(query = "", domain = "", repository = "", maturity = "", limit = 50, use_project = FALSE)
    expect_length(counter$calls, 0L)
    visible(TRUE)
    session$flushReact()
    expect_equal(counter$calls, "resources")
    expect_true("cytometry" %in% state$facets$domain)
    expect_true("CRAN" %in% state$facets$repository)
    expect_lte(nrow(state$results), 50L)
    visible(FALSE)
    visible(TRUE)
    session$flushReact()
    expect_length(counter$calls, 1L)
    session$setInputs(domain = "cytometry", repository = "Bioconductor", search = 1)
    expect_gt(nrow(state$results), 0L)
    expect_true(all(state$results$category == "cytometry"))
    expect_true(all(state$results$repository == "Bioconductor"))
    html <- as.character(output$results$html)
    expect_match(html, "Candidate", fixed = TRUE)
    expect_match(html, 'data-label="Maturity"', fixed = TRUE)
    session$setInputs(maturity = "tested")
    expect_equal(nrow(filtered()), 0L)
    session$setInputs(limit = 0, search = 2)
    expect_equal(state$status$key, "resources.limit_invalid")
  })
  status <- app_resource_maturity(data.frame(adapter_status = c("not_implemented", "adapter_tested", "untested", NA)))
  expect_equal(status, c("candidate", "tested", "candidate", "candidate"))
})

test_that("Audit filters checks, exports reports and applies allowlisted repairs", {
  skip_if_not_installed("shiny")
  p <- project("Audit fixture", "methods", "Goal", new_parent())
  reports <- file.path(new_parent(), "reports")
  shiny::testServer(app_audit_server, args = app_test_args(project = shiny::reactive(p$path)), {
    session$setInputs(scope = "project", path = p$path, live = FALSE, show = app_audit_statuses, required_only = FALSE)
    session$setInputs(repair = 1)
    expect_equal(state$status$key, "audit.repair_preview_first")
    session$setInputs(run = 1)
    expect_s3_class(state$result, "cttir_audit")
    expect_match(as.character(output$summary$html), "Overall status", fixed = TRUE)
    expect_match(as.character(output$repair_preview$html), "No failed check", fixed = TRUE)
    unlink(file.path(p$path, "code", "validate_project.R"))
    session$setInputs(run = 2)
    expect_equal(state$result$overall_status, "fail")
    preview <- as.character(output$repair_preview$html)
    expect_match(preview, "PRJ-002", fixed = TRUE)
    expect_match(preview, "code/validate_project.R", fixed = TRUE)
    expect_match(as.character(output$summary$html), "allowlisted repair", fixed = TRUE)
    session$setInputs(show = "fail")
    expect_match(as.character(output$checks$html), "validate_project.R", fixed = TRUE)
    expect_false(grepl("Baseline matches", as.character(output$checks$html), fixed = TRUE))
    session$setInputs(repair = 2)
    expect_true(file.exists(file.path(p$path, "code", "validate_project.R")))
    expect_length(state$repaired, 1L)
    expect_equal(state$status$key, "audit.repaired")
    session$setInputs(output = reports, export = 1)
    expect_length(state$reports, 2L)
    expect_true(all(file.exists(state$reports)))
    expect_true(all(startsWith(state$reports, reports)))
    session$setInputs(scope = character(0))
    session$setInputs(run = 3)
    expect_equal(state$status$key, "audit.scope_required")
  })
})

test_that("Audit jobs can be cancelled and duplicate submissions are refused", {
  skip_if_not_installed("shiny")
  pending <- app_pending_worker()
  shiny::testServer(app_audit_server, args = app_test_args(pending$worker), {
    session$setInputs(scope = "installation", path = "", live = FALSE, show = app_audit_statuses, required_only = FALSE)
    session$setInputs(run = 1)
    session$setInputs(run = 2)
    expect_equal(pending$control$count, 1L)
    expect_equal(state$status$key, "status.duplicate")
    session$setInputs(cancel = 1)
    expect_equal(pending$control$killed, 1L)
    expect_equal(state$status$key, "status.cancelled")
    expect_null(state$result)
  })
})

test_that("Runtime setup plans without side effects and reports an unavailable runtime", {
  skip_if_not_installed("shiny")
  root <- file.path(new_parent(), "runtime")
  withr::local_options(cttiR.runtime_dir = root)
  local_mocked_bindings(runtime_request = function(...) abort_cttir("The local runtime request failed.", "cttir_runtime_unavailable"))
  shiny::testServer(app_runtime_server, args = app_test_args(), {
    session$setInputs(model = "auto", install = TRUE, offline = TRUE)
    expect_match(as.character(output$estimate$html), "GB", fixed = TRUE)
    session$setInputs(plan = 1)
    expect_equal(state$result$state, "planned")
    expect_false(dir.exists(root))
    expect_match(as.character(output$result$html), "Planned", fixed = TRUE)
    session$setInputs(run = 1)
    expect_equal(state$result$state, "blocked")
    expect_equal(state$status$key, "runtime.blocked")
    html <- as.character(output$result$html)
    expect_match(html, "Blocked", fixed = TRUE)
    expect_match(html, "acquisition is disabled", fixed = TRUE)
    session$setInputs(status_check = 1)
    expect_match(as.character(output$locality$html), "INS-002", fixed = TRUE)
    session$setInputs(model = "remote-cloud-model", plan = 2)
    expect_equal(state$status$kind, "error")
    expect_match(state$status$detail, "without cloud execution", fixed = TRUE)
  })
})

test_that("Home cards request views and Open validates the project root", {
  skip_if_not_installed("shiny")
  shiny::testServer(app_home_server, {
    session$setInputs(go_audit = 1)
    expect_equal(session$returned()$tab, "audit")
    session$setInputs(go_create = 1)
    expect_equal(session$returned()$tab, "create")
  })
  p <- project("Open fixture", "methods", "Goal", new_parent())
  shiny::testServer(app_open_server, args = app_test_args(), {
    session$setInputs(path = file.path(tempdir(), "no-such-project"), open = 1)
    expect_null(opened())
    expect_match(as.character(output$status$html), "Error", fixed = TRUE)
    session$setInputs(path = p$path, open = 2)
    expect_equal(opened(), normalizePath(p$path, winslash = "/"))
  })
})

test_that("the application server switches language and warns about unsaved drafts", {
  skip_if_not_installed("shiny")
  shiny::testServer(app_server(worker = app_test_worker), {
    session$setInputs(lang = "de", nav = "home")
    expect_equal(lang(), "de")
    session$setInputs(lang = "xx")
    expect_equal(lang(), "en")
    session$setInputs(nav = "create")
    session$setInputs(`create-name` = "Unsaved", `create-goal` = "Goal", `create-type` = "methods", `create-parent` = tempdir())
    expect_true(dirty())
    session$setInputs(nav = "audit")
    expect_equal(notices(), 1L)
    session$setInputs(nav = "home")
    expect_equal(notices(), 1L)
  })
})

test_that("view renderers tolerate unknown and missing result fields", {
  expect_s3_class(app_update_ui(structure(list(status = "planned", extra = list(a = 1)), class = "cttir_update"), "de"), "shiny.tag")
  expect_s3_class(app_setup_ui(structure(list(state = "planned"), class = "cttir_setup"), "en"), "shiny.tag")
  expect_s3_class(app_render_value(list(a = list(b = list(c = list(d = list(e = list(f = 1))))))), "shiny.tag")
  expect_match(as.character(app_table(data.frame(x = "<b>bold</b>"), "en")), "&lt;b&gt;", fixed = TRUE)
  expect_match(as.character(app_badge("pass", "de")), "Bestanden", fixed = TRUE)
  expect_match(as.character(app_badge("pass")), "cttir-badge-ok", fixed = TRUE)
  expect_equal(app_status_kind("conflict"), "fail")
  checks <- data.frame(id = c("PRJ-002:a", "PRJ-002:b", "PRJ-007", "KB-001"), status = c("fail", "warning", "fail", "fail"))
  expect_equal(app_repair_candidates(checks)$id, c("PRJ-002:a", "PRJ-007"))
})
