test_that("update preview leaves no store and rejects unsupported policies", {
  f <- local_update_fixture()
  plan <- update(dry_run = TRUE)
  expect_equal(plan$status, "planned")
  expect_false(plan$activation)
  expect_false(file.exists(f$store))
  expect_equal(update_knowledge(dry_run = TRUE)$new_id, plan$new_id)
  expect_error(update(mode = "remote"), class = "cttir_source_unavailable")
  expect_error(update(catalogs = "invalid"), class = "cttir_input_error")
  expect_error(update(sources = "missing", dry_run = TRUE), class = "cttir_input_error")
  expect_error(update(packages = "missing", dry_run = TRUE), class = "cttir_source_unavailable")
  expect_false(file.exists(f$store))
})

test_that("whole package updates remove exports, retain pins and roll back", {
  f <- local_update_fixture()
  first <- update()
  expect_true(first$activation)
  expect_equal(nrow(search("cttirFixtureA::old")), 1L)
  project <- project("Pinned project", "methods", "Goal", f$parent)
  pinned_files <- tree_hashes(project$path)
  writeLines(c("keep <- function(x = 2) x", "new <- function(y) y"), file.path(f$source, "R", "api.R"))
  writeLines(c("export(keep)", "export(new)"), file.path(f$source, "NAMESPACE"))
  second <- update()
  expect_true(second$activation)
  expect_true(any(second$api_diff$change == "export_removed" & second$api_diff$symbol == "old"))
  expect_true(any(second$api_diff$change == "export_changed" & second$api_diff$symbol == "keep"))
  expect_equal(nrow(search("cttirFixtureA::old")), 0L)
  expect_equal(nrow(search("cttirFixtureA::new")), 1L)
  expect_equal(nrow(search("cttirFixtureA::old", path = project$path)), 1L)
  expect_equal(tree_hashes(project$path), pinned_files)
  expect_equal(update()$status, "unchanged")
  before <- tree_hashes(f$store)
  expect_equal(rollback_knowledge(first$new_id)$status, "planned")
  expect_equal(tree_hashes(f$store), before)
  expect_true(rollback_knowledge(first$new_id, dry_run = FALSE)$activation)
  expect_equal(nrow(search("cttirFixtureA::old")), 1L)
  expect_equal(nrow(search("cttirFixtureA::new")), 0L)
  expect_equal(tree_hashes(project$path), pinned_files)
})

test_that("failed extraction and activation preserve the last complete pointer", {
  f <- local_update_fixture()
  update()
  pointer <- read_document(file.path(f$store, "active.json"))
  writeLines("broken <- function(", file.path(f$source, "R", "api.R"))
  expect_error(update(), class = "cttir_source_unavailable")
  expect_equal(read_document(file.path(f$store, "active.json")), pointer)
  expect_false(dir.exists(file.path(f$store, "write-lock")))
  writeLines("keep <- function(x = 9) x", file.path(f$source, "R", "api.R"))
  local_mocked_bindings(activate_catalog = function(...) abort_cttir("injected activation failure", "cttir_transaction_conflict"))
  expect_error(update(), class = "cttir_transaction_conflict")
  expect_equal(read_document(file.path(f$store, "active.json")), pointer)
  expect_equal(nrow(search("cttirFixtureA::old")), 1L)
})

test_that("combined local refresh preserves curation and historical resource pins", {
  f <- local_update_fixture()
  description <- readLines(file.path(f$source, "DESCRIPTION"))
  writeLines(sub("cttirFixtureA", "reflowR", description, fixed = TRUE), file.path(f$source, "DESCRIPTION"))
  old <- resources("reflowR", limit = 100)
  project <- project("Historical resources", "methods", "Goal", f$parent)
  result <- update()
  current <- resources("reflowR", limit = 100)
  expect_true(result$activation)
  expect_equal(nrow(current), nrow(old) + 1L)
  expect_true(all(current$purpose == old$purpose[[1]]))
  expect_true(all(current$adapter_status == old$adapter_status[[1]]))
  expect_true(any(current$repository == "Local" & current$observed_version == "1.0.0"))
  expect_equal(resources("reflowR", path = project$path, limit = 100), old)
  expect_equal(update()$status, "unchanged")
  expect_true(rollback_knowledge(result$previous_id, dry_run = FALSE)$activation)
  expect_equal(resources("reflowR", limit = 100), old)
})

test_that("resource staging failure never publishes an API-only partial update", {
  f <- local_update_fixture()
  update()
  pointer <- read_document(file.path(f$store, "active.json"))
  writeLines("keep <- function(x = 7) x", file.path(f$source, "R", "api.R"))
  local_mocked_bindings(refresh_resource_observations = function(...) abort_cttir("injected resource failure", "cttir_catalog_corrupt"))
  expect_error(update(), class = "cttir_catalog_corrupt")
  expect_equal(read_document(file.path(f$store, "active.json")), pointer)
  expect_equal(nrow(search("cttirFixtureA::old")), 1L)
})

test_that("corrupt historical snapshots cannot become active", {
  f <- local_update_fixture()
  first <- update()
  writeLines("keep <- function(x = 8) x", file.path(f$source, "R", "api.R"))
  update()
  pointer <- read_document(file.path(f$store, "active.json"))
  history <- file.path(f$store, "snapshots", first$catalogs$knowledge$current, "api-catalog.json.gz")
  writeLines("corrupt", history)
  expect_error(rollback_knowledge(first$new_id, dry_run = FALSE), class = "cttir_catalog_corrupt")
  expect_equal(read_document(file.path(f$store, "active.json")), pointer)
})

test_that("repeat creation and sync use project pins even if the global pointer is corrupt", {
  f <- local_update_fixture()
  p <- project("Independent pin", "methods", "Goal", f$parent)
  original <- tree_hashes(p$path)
  update()
  expect_equal(project("Independent pin", "methods", "Goal", f$parent)$path, p$path)
  writeLines("corrupt", file.path(f$store, "active.json"))
  expect_equal(project("Independent pin", "methods", "Goal", f$parent)$path, p$path)
  expect_equal(sync(p$path)$state, "planned")
  expect_equal(tree_hashes(p$path), original)
})

test_that("creation rejects catalog changes after preview or during planning", {
  f <- local_update_fixture()
  expected <- content_hash(json_text(current_catalog_manifest()))
  update()
  expect_error(project_impl("Stale creation", "methods", "Goal", f$parent, expected_catalog = expected), class = "cttir_transaction_conflict")
  expect_false(dir.exists(file.path(f$parent, "stale_creation")))
  local_mocked_bindings(resource_snapshot = function(...) list(id = paste(rep("a", 64), collapse = "")))
  expect_error(project("Mixed snapshot", "methods", "Goal", f$parent), class = "cttir_transaction_conflict")
  expect_false(dir.exists(file.path(f$parent, "mixed_snapshot")))
})
