test_that("audit is read-only, scope-aware and strict about actual failures", {
  parent <- new_parent()
  p <- project("Audit", "methods", "Goal", parent)
  before <- tree_hashes(p$path)
  report <- audit(p$path, scope = "project", strict = TRUE)
  expect_s3_class(report, "cttir_audit")
  expect_equal(report$overall_status, "warning")
  expect_identical(tree_hashes(p$path), before)
  expect_equal(audit(scope = "project")$overall_status, "not_tested")
  expect_error(audit(scope = "invalid"), class = "cttir_input_error")
  expect_error(audit(scope = character()), class = "cttir_input_error")
  expect_s3_class(doctor(), "cttir_audit")
  expect_equal(as.data.frame(report), report$checks)
  unlink(file.path(p$path, "code/validate_project.R"))
  reports <- file.path(parent, "reports")
  error <- tryCatch(audit(p$path, scope = "project", strict = TRUE, output = reports), error = identity)
  expect_s3_class(error, "cttir_audit_failed")
  expect_equal(error$report$overall_status, "fail")
  expect_length(list.files(reports), 2L)
  expect_false(file.exists(file.path(p$path, "code/validate_project.R")))
})

test_that("repair restores only verified missing managed files", {
  parent <- new_parent()
  p <- project("Repair", "methods", "Goal", parent)
  original <- readLines(file.path(p$path, "code/validate_project.R"))
  unlink(file.path(p$path, "code/validate_project.R"))
  manuscript <- file.path(p$path, "publications/pub01_main/manuscript/README.md")
  writeLines("Keep the manuscript", manuscript)
  a <- audit(p$path, scope = "project", repair = TRUE)
  expect_length(a$repairs, 1L)
  expect_equal(readLines(file.path(p$path, "code/validate_project.R")), original)
  expect_equal(readLines(manuscript), "Keep the manuscript")
  expect_length(audit(p$path, scope = "project", repair = TRUE)$repairs, 0L)
  writeLines("# Reviewed local changes", file.path(p$path, "code/validate_project.R"))
  expect_length(audit(p$path, scope = "project", repair = TRUE)$repairs, 0L)
  expect_equal(readLines(file.path(p$path, "code/validate_project.R")), "# Reviewed local changes")
})

test_that("a repair is bound to the previewed plan, which lists its target files", {
  parent <- new_parent()
  p <- project("Bound repair", "methods", "Goal", parent)
  demo <- file.path(p$path, "code", "run_demo.R")
  report <- file.path(p$path, "code", "render_report.R")
  expect_length(audit(p$path, scope = "project")$repair_plan, 0L)
  unlink(demo)
  preview <- audit(p$path, scope = "project")
  plan <- preview$repair_plan
  expect_length(plan, 1L)
  expect_equal(plan[[1]]$id, "restore_missing_managed")
  expect_equal(plan[[1]]$status, "planned")
  expect_equal(plan[[1]]$trigger, "PRJ-002")
  expect_named(plan[[1]]$targets, "code/run_demo.R")
  expect_true(is.na(plan[[1]]$targets[["code/run_demo.R"]]))
  expected <- audit_plan_fingerprint(plan)
  unlink(report)
  before <- tree_state(p$path)
  expect_error(audit_impl(p$path, scope = "project", repair = TRUE, expected_plan = expected), class = "cttir_transaction_conflict")
  expect_identical(tree_state(p$path), before)
  current <- audit_plan_fingerprint(audit(p$path, scope = "project")$repair_plan)
  repaired <- audit_impl(p$path, scope = "project", repair = TRUE, expected_plan = current)
  expect_equal(repaired$repairs[[1]]$status, "applied")
  expect_true(all(file.exists(c(demo, report))))
  expect_length(repaired$repair_plan, 0L)

  skip_if_not_installed("shiny")
  shiny::testServer(app_audit_server, args = app_test_args(project = shiny::reactive(p$path)), {
    session$setInputs(scope = "project", path = p$path, live = FALSE, show = app_audit_statuses, required_only = FALSE)
    session$setInputs(run = 1)
    expect_match(as.character(output$repair_preview$html), "No failed check", fixed = TRUE)
    unlink(demo)
    session$setInputs(repair = 1)
    expect_equal(state$status$key, "status.stale_files")
    expect_false(file.exists(demo))
    html <- as.character(output$repair_preview$html)
    expect_match(html, "code/run_demo.R", fixed = TRUE)
    expect_match(html, "restore_missing_managed", fixed = TRUE)
    expect_match(html, "PRJ-002", fixed = TRUE)
    unlink(report)
    session$setInputs(repair = 2)
    expect_equal(state$status$key, "status.stale_files")
    expect_false(any(file.exists(c(demo, report))))
    expect_match(as.character(output$repair_preview$html), "code/render_report.R", fixed = TRUE)
    session$setInputs(repair = 3)
    expect_equal(state$status$key, "audit.repaired")
    expect_true(all(file.exists(c(demo, report))))
    session$setInputs(repair = 4)
    expect_equal(state$status$key, "audit.repair_preview_first")
  })
})
