test_that("three-input creation is offline, useful and idempotent", {
  parent <- new_parent()
  before_rng <- if (exists(".Random.seed", .GlobalEnv)) get(".Random.seed", .GlobalEnv) else NULL
  before_wd <- getwd()
  before_lib <- .libPaths()
  preview <- project("Example Study", "primary_research", "Describe outcomes", parent, dry_run = TRUE)
  expect_length(list.files(parent, all.files = TRUE, no.. = TRUE), 0)
  expect_false(preview$readiness$materialized)
  p <- project("Example Study", "primary_research", "Describe outcomes", parent)
  expect_equal(p$path, file.path(normalizePath(parent, winslash = "/"), "example_study"))
  expect_equal(p$spec$research$ethics_status, "unknown")
  expect_false(p$spec$analysis$approved)
  expect_true(file.exists(file.path(p$path, "publications/pub01_main/manuscript/README.md")))
  expect_true(file.exists(file.path(p$path, "code/validate_project.R")))
  expect_silent(validate_spec(file.path(p$path, "cttir-project.yml")))
  original <- tree_hashes(p$path)
  repeat_p <- project("Example Study", "primary_research", "Describe outcomes", parent)
  expect_identical(tree_hashes(p$path), original)
  expect_identical(p$spec, repeat_p$spec)
  expect_true(all(repeat_p$plan$action == "skip"))
  expect_equal(getwd(), before_wd)
  expect_equal(.libPaths(), before_lib)
  expect_identical(if (exists(".Random.seed", .GlobalEnv)) get(".Random.seed", .GlobalEnv) else NULL, before_rng)
  expect_error(project("Example Study", "methods", "Changed goal", parent), class = "cttir_path_conflict")
  expect_identical(tree_hashes(p$path), original)
})

test_that("user edits survive identical creation and dry run", {
  parent <- new_parent()
  p <- project("Edits", "methods", "Preserve work", parent)
  writeLines("Reviewed manuscript", file.path(p$path, "publications/pub01_main/manuscript/README.md"))
  writeLines("# Custom validation", file.path(p$path, "code/validate_project.R"))
  before <- tree_hashes(p$path)
  rerun <- project("Edits", "methods", "Preserve work", parent)
  expect_contains(rerun$warnings, "existing_edits_preserved")
  expect_identical(tree_hashes(p$path), before)
  expect_s3_class(project("Edits", "methods", "Preserve work", parent, dry_run = TRUE), "cttir_project")
  expect_identical(tree_hashes(p$path), before)
  unlink(file.path(p$path, "cttir-lock.json"))
  expect_error(project("Edits", "methods", "Preserve work", parent), class = "cttir_path_conflict")
})

test_that("unsafe paths, symlinks and writer collisions are contained", {
  parent <- new_parent()
  for (name in c("../escape", "CON", "a/b", "a\\b", "..", "nul", "com1")) {
    expect_error(project(name, "methods", "Goal", parent), class = "cttir_input_error")
  }
  writeLines("Keep me", file.path(parent, "collision"))
  expect_error(project("Collision", "methods", "Goal", parent), class = "cttir_path_conflict")
  dir.create(file.path(parent, ".locked.cttir-create-lock"))
  expect_error(project("Locked", "methods", "Goal", parent), class = "cttir_transaction_conflict")
  expect_false(dir.exists(file.path(parent, "locked")))
  expect_equal(readLines(file.path(parent, "collision")), "Keep me")
  if (.Platform$OS.type != "windows") {
    outside <- new_parent()
    expect_true(file.symlink(outside, file.path(parent, "linked")))
    expect_error(project("Linked", "methods", "Goal", parent), class = "cttir_path_conflict")
    expect_error(project("New", "methods", "Goal", file.path(parent, "linked")), class = "cttir_path_conflict")
    expect_length(list.files(outside, all.files = TRUE, no.. = TRUE), 0)
  }
})

test_that("unicode is retained as data and generated R remains fixed", {
  parent <- new_parent()
  p <- project("München Study", "mixed", "```r print('no execution') ``` <script>bad()</script>", parent)
  expect_identical(p$spec$project$name, "München Study")
  code <- paste(readLines(file.path(p$path, "code/validate_project.R")), collapse = "\n")
  expect_false(grepl("no execution|<script>", code))
  expect_type(parse(text = code), "expression")
})

test_that("a creation lock left by a stopped process is recovered on retry", {
  skip_if_not_installed("callr")
  parent <- new_parent()
  lock <- file.path(parent, ".crashed.cttir-create-lock")
  stage <- file.path(parent, ".crashed-stage-1a2b3c")
  dir.create(lock)
  dir.create(file.path(stage, "code"), recursive = TRUE)
  writeLines("staged", file.path(stage, "code/run_demo.R"))
  dir.create(file.path(parent, ".other-stage-4d5e"))
  writeLines("Keep me", file.path(parent, "notes.txt"))
  write_bytes(json_text(list(pid = dead_pid(), host = Sys.info()[["nodename"]], stage = basename(stage))),
    file.path(lock, "owner.json"))
  preview <- project("Crashed", "methods", "Goal", parent, dry_run = TRUE)
  expect_contains(preview$warnings, "stale_creation_lock")
  expect_true(dir.exists(lock))
  p <- project("Crashed", "methods", "Goal", parent)
  expect_true(dir.exists(p$path))
  expect_contains(p$warnings, "stale_creation_lock_recovered")
  expect_equal(p$recovered[[1]]$reason, "owner_gone")
  expect_equal(unlist(p$recovered[[1]]$staging_removed), basename(stage))
  expect_setequal(list.files(parent, all.files = TRUE, no.. = TRUE), c("crashed", ".other-stage-4d5e", "notes.txt"))
  expect_output(print(p), "Recovered")
})

test_that("held or unverifiable creation locks are refused with the next step", {
  skip_if_not_installed("callr")
  parent <- new_parent()
  lock <- file.path(parent, ".busy.cttir-create-lock")
  dir.create(lock)
  write_bytes(json_text(list(pid = Sys.getpid(), host = Sys.info()[["nodename"]])), file.path(lock, "owner.json"))
  err <- expect_error(project("Busy", "methods", "Goal", parent), "running cttiR process", class = "cttir_transaction_conflict")
  expect_match(err$remediation, "Wait for the other project")
  write_bytes(json_text(list(pid = dead_pid(), host = "another-host")), file.path(lock, "owner.json"))
  expect_error(project("Busy", "methods", "Goal", parent), "another-host", class = "cttir_transaction_conflict")
  unlink(file.path(lock, "owner.json"))
  err <- expect_error(project("Busy", "methods", "Goal", parent), "no owner record", class = "cttir_transaction_conflict")
  expect_match(err$remediation, "remove the directory .busy.cttir-create-lock")
  expect_false(dir.exists(file.path(parent, "busy")))
  # An ownerless lock from an older version is recovered only once it is old.
  dir.create(file.path(parent, ".busy-stage-77aa"))
  old <- Sys.time() - 2 * stale_lock_seconds
  Sys.setFileTime(lock, old)
  p <- project("Busy", "methods", "Goal", parent)
  expect_equal(p$recovered[[1]]$reason, "ownerless_lock_expired")
  expect_equal(unlist(p$recovered[[1]]$staging_removed), ".busy-stage-77aa")
  expect_identical(list.files(parent, all.files = TRUE, no.. = TRUE), "busy")
})

test_that("names without a transliteration get stable, distinct slugs and clear messages", {
  parent <- new_parent()
  plan <- function(name) project(name, "methods", "Goal", parent, dry_run = TRUE)
  japanese <- plan("日本語の研究")
  expect_match(basename(japanese$path), "^project_[0-9a-f]{8}$")
  expect_identical(japanese$spec$project$name, "日本語の研究")
  expect_identical(basename(plan("日本語の研究")$path), basename(japanese$path))
  mixed <- basename(plan("Étude 名前")$path)
  expect_match(mixed, "^etude_[0-9a-f]{8}$")
  expect_false(identical(mixed, basename(plan("Étude 研究")$path)))
  expect_identical(basename(plan("Ünïcödé Prøject Ærø")$path), "unicode_project_aero")
  expect_identical(basename(plan("\U0001F680 rocket")$path), "rocket")
  long <- paste(rep("long", 40), collapse = " ")
  slug <- basename(plan(long)$path)
  expect_lte(nchar(slug), 80L)
  expect_match(slug, "^long_long.*_[0-9a-f]{8}$")
  expect_false(identical(slug, basename(plan(paste(long, "two"))$path)))
  expect_error(plan("CON"), "reserved Windows device name 'con'", class = "cttir_input_error")
  expect_error(plan("!!!"), "at least one letter or digit", class = "cttir_input_error")
  reserved <- list(publications = list(list(id = "pub01", slug = "con")))
  expect_error(project("Pubs", "methods", "Goal", parent, options = reserved, dry_run = TRUE),
    "slug 'con' is a reserved Windows device name", class = "cttir_input_error")
})

test_that("a repeat project() stays read-only after sync updated or kept user-owned files", {
  parent <- new_parent()
  p <- project("Repeat after sync", "primary_research", "Describe a cohort", parent)
  again <- function() project("Repeat after sync", "primary_research", "Describe a cohort", parent)
  source <- list(id = "ds1", label = "Cohort", logical_uri = NULL, format = "csv", access_class = "restricted",
    checksum = NULL, checksum_status = "unknown", schema_ref = NULL)
  sync(p$path, options = list(data_sources = list(source)), dry_run = FALSE)
  state <- tree_state(p$path)
  expect_true(all(again()$plan$action == "skip"))
  expect_identical(tree_state(p$path), state)
  registry <- file.path(p$path, "metadata/data-registry.yml")
  cat("# reviewed\n", file = registry, append = TRUE)
  source$label <- "Cohort 2026"
  applied <- sync(p$path, options = list(data_sources = list(source)), dry_run = FALSE)
  expect_equal(applied$pending_updates$path, "metadata/data-registry.yml")
  state <- tree_state(p$path)
  expect_contains(again()$warnings, "existing_edits_preserved")
  expect_identical(tree_state(p$path), state)
  # Taking over the proposal by hand keeps the repeat read-only as well.
  file.copy(file.path(p$path, ".cttir/proposed/metadata/data-registry.yml"), registry, overwrite = TRUE)
  state <- tree_state(p$path)
  expect_true(all(again()$plan$action == "skip"))
  expect_identical(tree_state(p$path), state)
})

test_that("analysis plans list the unknowns of each research type without inventing content", {
  parent <- new_parent()
  goal <- "Compare blood pressure between two groups"
  plans <- list()
  for (type in c("primary_research", "secondary_research", "methods", "review", "software", "mixed", "other")) {
    p <- project(paste("Plan", type), type, goal, parent, dry_run = TRUE)
    plans[[type]] <- project_bundle(p$spec)$files[["protocol/analysis-plan.md"]]
  }
  expect_length(unique(plans), 7L)
  for (text in plans) {
    expect_false(grepl("blood pressure", text, fixed = TRUE))
    expect_match(text, "Every item below is unknown")
    expect_match(text, "- TODO: ")
  }
  expect_match(plans$primary_research, "Estimand")
  expect_match(plans$primary_research, "Primary outcome and its timepoint")
  expect_match(plans$secondary_research, "Search strategy for each source")
  expect_match(plans$secondary_research, "No literature search has been run")
  expect_match(plans$review, "the review type is unknown")
  expect_match(plans$methods, "Simulation design")
  expect_match(plans$methods, "Benchmark datasets")
  expect_match(plans$software, "Test plan")
  expect_match(plans$software, "Licensing decision")
  expect_match(plans$mixed, "Shared across publications")
  expect_match(plans$other, "Question or objective")
  expect_false(grepl("Estimand", plans$software, fixed = TRUE))
  review_pub <- list(id = "pub02", title = "Review", slug = "pub02_review", type = "systematic_review",
    research_class = "secondary_research", analysis_role = "unknown", data_origin = "literature")
  mixed <- project("Plan mixed two", "mixed", goal, parent, options = list(publications = list(review_pub)), dry_run = TRUE)
  text <- project_bundle(mixed$spec)$files[["protocol/analysis-plan.md"]]
  expect_match(text, "## Search and selection (secondary research publications)", fixed = TRUE)
  expect_match(text, "No literature search has been run")
})
