test_that("audit is read-only, scope-aware and strict about actual failures", {
  parent <- new_parent()
  p <- project("Audit", "methods", "Goal", parent)
  before <- tree_hashes(p$path)
  report <- audit(p$path, scope = "project", strict = TRUE)
  expect_s3_class(report, "cttir_audit")
  expect_equal(report$overall_status, "warning")
  expect_identical(tree_hashes(p$path), before)
  expect_equal(audit(scope = "project")$overall_status, "not_tested")
  expect_error(audit(scope = "invalid"), class = "cttir_input_error")
  expect_error(audit(scope = character()), class = "cttir_input_error")
  expect_s3_class(doctor(), "cttir_audit")
  expect_equal(as.data.frame(report), report$checks)
  unlink(file.path(p$path, "code/validate_project.R"))
  reports <- file.path(parent, "reports")
  error <- tryCatch(audit(p$path, scope = "project", strict = TRUE, output = reports), error = identity)
  expect_s3_class(error, "cttir_audit_failed")
  expect_equal(error$report$overall_status, "fail")
  expect_length(list.files(reports), 2L)
  expect_false(file.exists(file.path(p$path, "code/validate_project.R")))
})

test_that("repair restores only verified missing managed files", {
  parent <- new_parent()
  p <- project("Repair", "methods", "Goal", parent)
  original <- readLines(file.path(p$path, "code/validate_project.R"))
  unlink(file.path(p$path, "code/validate_project.R"))
  manuscript <- file.path(p$path, "publications/pub01_main/manuscript/README.md")
  writeLines("Keep the manuscript", manuscript)
  a <- audit(p$path, scope = "project", repair = TRUE)
  expect_length(a$repairs, 1L)
  expect_equal(readLines(file.path(p$path, "code/validate_project.R")), original)
  expect_equal(readLines(manuscript), "Keep the manuscript")
  expect_length(audit(p$path, scope = "project", repair = TRUE)$repairs, 0L)
  writeLines("# Reviewed local changes", file.path(p$path, "code/validate_project.R"))
  expect_length(audit(p$path, scope = "project", repair = TRUE)$repairs, 0L)
  expect_equal(readLines(file.path(p$path, "code/validate_project.R")), "# Reviewed local changes")
})
