interrupted_fixture <- function(root, pid) {
  relative <- "code/validate_project.R"
  dest <- file.path(root, relative)
  before <- file_hash(dest)
  dir <- file.path(root, ".cttir/transactions/interrupted-test")
  dir.create(file.path(dir, "backup"), recursive = TRUE)
  file.copy(dest, file.path(dir, "backup/1"))
  write_bytes("# Interrupted replacement\n", dest)
  actions <- data.frame(path = relative, action = "update", old_hash = before, new_hash = file_hash(dest))
  write_bytes(json_text(list(schema_version = 1L, status = "applying", actions = actions)), file.path(dir, "journal.json"))
  write_bytes(json_text(list(pid = pid, host = Sys.info()[["nodename"]])), file.path(root, ".cttir/write-lock/owner.json"))
  before
}

test_that("interrupted transactions restore only matching preimages", {
  skip_if_not_installed("callr")
  parent <- new_parent()
  p <- project("Interrupted", "methods", "Goal", parent)
  dead_pid <- callr::r(function() Sys.getpid())
  baseline <- interrupted_fixture(p$path, dead_pid)
  before <- tree_hashes(p$path)
  expect_equal(audit(p$path, scope = "project")$overall_status, "fail")
  expect_identical(tree_hashes(p$path), before)
  result <- audit(p$path, scope = "project", repair = TRUE)
  expect_equal(result$repairs[[1]]$id, "recover_interrupted_transaction")
  expect_equal(file_hash(file.path(p$path, "code/validate_project.R")), baseline)
  expect_false(dir.exists(file.path(p$path, ".cttir/write-lock")))
  expect_length(pending_transactions(p$path), 0L)
})

test_that("recovery refuses active writers and post-interruption edits", {
  skip_if_not_installed("callr")
  parent <- new_parent()
  p <- project("Active", "methods", "Goal", parent)
  interrupted_fixture(p$path, Sys.getpid())
  expect_error(recover_transactions(p$path), "still running", class = "cttir_transaction_conflict")
  owner <- file.path(p$path, ".cttir/write-lock/owner.json")
  write_bytes(json_text(list(pid = callr::r(function() Sys.getpid()), host = Sys.info()[["nodename"]])), owner)
  target <- file.path(p$path, "code/validate_project.R")
  writeLines("# User edits after interruption", target)
  before <- tree_hashes(p$path)
  expect_error(recover_transactions(p$path), "changed after interruption", class = "cttir_transaction_conflict")
  expect_identical(tree_hashes(p$path), before)
})

test_that("a writer lock left before any journal is released by sync and by audit repair", {
  skip_if_not_installed("callr")
  parent <- new_parent()
  p <- project("Stale writer", "methods", "Goal", parent)
  lock <- file.path(p$path, ".cttir/write-lock")
  stale_lock <- function(pid) {
    dir.create(lock, showWarnings = FALSE)
    write_bytes(json_text(list(pid = pid, host = Sys.info()[["nodename"]])), file.path(lock, "owner.json"))
  }
  stale_lock(dead_pid())
  before <- tree_hashes(p$path)
  report <- audit(p$path, scope = "project")
  expect_equal(report$checks$status[report$checks$id == "PRJ-007"], "fail")
  expect_identical(tree_hashes(p$path), before)
  repaired <- audit(p$path, scope = "project", repair = TRUE)
  expect_equal(repaired$repairs[[1]]$status, "applied")
  expect_equal(repaired$checks$status[repaired$checks$id == "PRJ-007"], "pass")
  expect_false(dir.exists(lock))
  stale_lock(dead_pid())
  preview <- sync(p$path, options = list(analysis = list(aim = "descriptive")))
  expect_equal(preview$writer_lock$state, "stale")
  applied <- sync(p$path, options = list(analysis = list(aim = "descriptive")), dry_run = FALSE)
  expect_equal(applied$state, "applied")
  expect_equal(applied$recovered[[1]]$id, "release_stale_writer_lock")
  expect_null(applied$writer_lock)
  expect_false(dir.exists(lock))
  # A running owner or an ownerless lock is never taken over.
  stale_lock(Sys.getpid())
  err <- expect_error(sync(p$path, options = list(analysis = list(aim = "explanatory")), dry_run = FALSE),
    "running cttiR process", class = "cttir_transaction_conflict")
  expect_match(err$remediation, "Wait for the other cttiR operation")
  expect_length(recover_transactions(p$path), 0L)
  unlink(file.path(lock, "owner.json"))
  err <- expect_error(sync(p$path, options = list(analysis = list(aim = "explanatory")), dry_run = FALSE),
    "no owner record", class = "cttir_transaction_conflict")
  expect_match(err$remediation, "remove the directory .cttir/write-lock")
  expect_true(dir.exists(lock))
})
