test_that("the real resource seed remains intact and searchable", {
  db <- system.file("extdata", "package-resources.sqlite", package = "cttiR")
  before <- digest::digest(file = db, algo = "sha256")
  con <- DBI::dbConnect(RSQLite::SQLite(), db, flags = RSQLite::SQLITE_RO)
  on.exit(DBI::dbDisconnect(con))
  expect_equal(DBI::dbGetQuery(con, "PRAGMA integrity_check")[[1]], "ok")
  expect_equal(nrow(DBI::dbGetQuery(con, "PRAGMA foreign_key_check")), 0L)
  expect_equal(DBI::dbGetQuery(con, "SELECT count(*) AS n FROM packages")$n, 229)
  all <- resources(limit = 10000)
  expect_equal(length(unique(all$package_id)), 229)
  expect_true(all(all$adapter_status == "not_implemented"))
  r <- resources("cytometry", repository = "Bioconductor", limit = 3)
  expect_equal(nrow(r), 3L)
  expect_true(all(r$repository == "Bioconductor"))
  expect_equal(resources("Seurat", limit = 1)$name, "Seurat")
  expect_equal(nrow(resources("' OR 1=1 --")), 0L)
  expect_equal(nrow(resources("%")), 0L)
  expect_equal(digest::digest(file = db, algo = "sha256"), before)
  for (limit in list(0, NA, Inf, 1.1, "10", c(1, 2))) expect_error(resources(limit = limit), class = "cttir_input_error")
})

test_that("project resource queries honor pins without fallback", {
  parent <- new_parent()
  p <- project("Pinned", "methods", "Goal", parent)
  expect_equal(resources("Seurat", path = p$path), resources("Seurat"))
  lock <- file.path(p$path, "cttir-lock.json")
  x <- jsonlite::fromJSON(lock, simplifyVector = FALSE)
  x$resource_snapshot <- "missing-snapshot"
  jsonlite::write_json(x, lock, auto_unbox = TRUE)
  expect_error(resources(path = p$path), class = "cttir_source_unavailable")
})

test_that("the compressed JSON mirror is the imported file and matches the database", {
  parity <- resource_json_parity()
  expect_true(parity$hash_matches)
  expect_gte(parity$tables, 10L)
  expect_length(parity$mismatched_tables, 0L)
})
